Repository woongteco/nextcamp-12t, pull requests merged in 2024-08, with the labels that each got.

#118 [Fix] 프로필 정보 업데이트 기능 오류 수정, 헤더 프로필 이미지 변경 적용
  src/app/(auth)/_components/LoginForm.tsx
  src/app/(auth)/_components/RegisterForm.tsx
  src/app/(route)/_components/LikeIconButton.tsx
  src/app/(route)/_components/ShareIconButton.tsx
  src/app/(route)/my/layout.tsx
  src/app/(route)/my/post/page.tsx
  src/app/(route)/my/profile/_components/DeleteAccountConfirm.tsx
  src/app/(route)/my/profile/_components/EditProfile/FormEditProfile.tsx
  src/app/(route)/my/profile/_components/EditProfile/ProfileFormsAndPreview.tsx
  src/app/(route)/my/profile/_components/EditProfile/ProfilePreview.tsx
  src/app/(route)/my/profile/_components/EditProfileImage/FormEditProfileImageWithPreview.tsx
  src/app/(route)/my/profile/_components/FormEditProfile.tsx
  src/app/(route)/my/profile/_components/ProfileForms.tsx
  src/app/(route)/my/profile/_components/UpdatePassword/FormUpdatePassword.tsx
  src/app/(route)/my/profile/_components/UpdatePhoneNumber/FormUpdatePhoneNumber.tsx
  src/app/(route)/my/profile/page.tsx
  src/app/(route)/my/study/page.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/_components/IconButtonActionsInDetail.tsx
  src/app/(route)/post/_components/LinkedStudyCard.tsx
  src/app/(route)/post/page.tsx
  src/app/(route)/post/write/[postId]/page.tsx
  src/app/(route)/post/write/_components/CustomizedStudySelect.tsx
  src/app/(route)/post/write/_components/PostForm.tsx
  src/app/(route)/post/write/_components/SelectCategory.tsx
  src/app/(route)/post/write/_components/SelectLinkedStudy.tsx
  src/app/(route)/post/write/page.tsx
  src/app/(route)/study/_components/StudyCategorySelectBox.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/app/_components/RecommendLatestStudies.tsx
  src/app/_components/RecommendProStudies.tsx
  src/app/_components/SetCategoryFavor.tsx
  src/app/_components/TopBannerSearchbar.tsx
  src/app/_components/TopBannerSection.tsx
  src/app/globals.css
  src/app/loading.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/set-category/page.tsx
  src/common/Atoms/Image/ProfileImg.tsx
  src/common/Atoms/Text/SectionTitle.tsx
  src/common/Layout/Header.tsx
  src/common/Layout/LoadingContainer.tsx
  src/common/Layout/SessionedHeader.tsx
  src/common/Molecules/Form/ButtonCheck.tsx
  src/common/Molecules/ModalPortal/ModalPortal.tsx
  src/common/Organisms/PostListItem.tsx
  src/constants/categories/job_category.ts
  src/dummies/utils.ts
  src/hooks/useModal.tsx
  src/lib/actions/authAction.ts
  src/lib/actions/communityAction.ts
  src/lib/actions/profileAction.ts
  src/lib/actions/studyAction.ts
  src/lib/actions/userAction.ts
  src/types/model/User.ts
  tsconfig.json
Labels: bug fix, refactor, feature

#121 [Fix] 유저 스키마 수정
  src/app/(route)/_components/DeletePostButton.tsx
  src/app/(route)/_components/LikeIconButton.tsx
  src/app/(route)/my/like-study/page.tsx
  src/app/(route)/my/post/page.tsx
  src/app/(route)/my/profile/_components/EditProfile/FormEditProfile.tsx
  src/app/(route)/my/profile/_components/EditProfileImage/FormEditProfileImageWithPreview.tsx
  src/app/(route)/my/profile/_components/EditProfileImage/ProfileImagePreviewModal.tsx
  src/app/(route)/my/profile/_components/ProfileForms.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/_components/IconButtonActionsInDetail.tsx
  src/app/(route)/post/_components/LinkedStudyCard.tsx
  src/app/(route)/post/_components/ReturnToListButton.tsx
  src/app/(route)/post/page.tsx
  src/app/(route)/post/write/[postId]/page.tsx
  src/app/(route)/post/write/_components/CustomizedStudySelect.tsx
  src/app/(route)/post/write/_components/PostForm.tsx
  src/app/(route)/post/write/_components/SelectCategory.tsx
  src/app/(route)/post/write/_components/SelectLinkedStudy.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/LargeStudyList.tsx
  src/app/(route)/study/_components/StudyCardFilter.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/_components/WideStudyList.tsx
  src/app/(route)/study/create/_components/StudyForm.tsx
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/app/_components/RecommendProStudies.tsx
  src/auth.ts
  src/common/Atoms/Form/InputElement.tsx
  src/common/Layout/Header.tsx
  src/common/Molecules/Form/ImageInputWithButton.tsx
  src/common/Molecules/Profile.tsx
  src/common/Organisms/Comment/CommentItem.tsx
  src/common/Organisms/ContentArea.tsx
  src/common/Organisms/PostListItem.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Organisms/customContent.module.css
  src/common/Templates/CardList.tsx
  src/common/Templates/PostList.tsx
  src/common/Templates/PostListWithPagination.tsx
  src/constants/categories/job_category.ts
  src/constants/categories/study_goal.ts
  src/constants/categories/study_type.ts
  src/constants/null_user.ts
  src/dummies/posts.ts
  src/dummies/studies.ts
  src/lib/actions/authAction.ts
  src/lib/actions/communityAction.ts
  src/lib/actions/profileAction.ts
  src/lib/actions/studyAction.ts
  src/lib/actions/userAction.ts
  src/lib/schema.ts
  src/types/component/props.ts
  src/types/model/Category.ts
  src/types/model/Comment.ts
  src/types/model/PostItem.ts
  src/types/model/Profile.ts
  src/types/model/StudyCard.ts
  src/types/model/User.ts
Labels: docs, merge, style, feature

#122 [Feat] 스터디 개설하기 페이지 StudyForm완료
  src/app/(route)/study/create/_components/StudyForm.tsx
  src/app/(route)/study/create/page.tsx
  src/common/Atoms/Form/DateRange.tsx
Labels: merge, 검토중, feature

#128 [Feat, Fix] study api form전송, studyList Components
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/StudyCardFilter.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/_components/WideStudyList.tsx
  src/app/(route)/study/create/_components/StudyForm.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CardList.tsx
  src/lib/actions/studyAction.ts
  src/lib/schema.ts
  src/types/model/StudyCard.ts
Labels: bug, merge, feature

#131 [Feat] 계정 별 알림 진행중
  public/icons/AlarmIcon.svg
  src/app/(auth)/_components/FindAuthForm.tsx
  src/app/(auth)/_components/FindNoData.tsx
  src/app/(auth)/_components/RegisterForm.tsx
  src/app/(auth)/_components/UserInput.tsx
  src/app/(auth)/find/email/page.tsx
  src/app/(auth)/find/password/page.tsx
  src/app/_components/AlertList.tsx
  src/app/api/comment/route.ts
  src/auth.ts
  src/common/Layout/Header.tsx
  src/common/Layout/ProfileMenu/DesktopMenu.tsx
  src/common/Layout/ProfileMenu/ResponsiveMenu.tsx
  src/common/Layout/SessionedHeader.tsx
  src/lib/actions/AlertAction.ts
  src/lib/actions/authAction.ts
  src/lib/actions/commentAction.ts
  src/lib/actions/communityAction.ts
  src/lib/actions/replyAction.ts
  src/lib/schema.ts
  src/middleware.ts
  src/store/useFindEmail.ts
  src/utils/customFetch.ts
  src/utils/formatPhoneNumber.ts
Labels: merge, style, feature

#132 [Feat] study 상세페이지 data api
  src/app/(route)/study/[studyPostId]/_components/Comment.tsx
  src/app/(route)/study/[studyPostId]/_components/CommentList.tsx
  src/app/(route)/study/[studyPostId]/_components/CommentReply.tsx
  src/app/(route)/study/[studyPostId]/_components/LeaderProfile.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetail.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailContent.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailThumbnail.tsx
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/AccordionComponent.tsx
  src/app/(route)/study/_components/AccordionList.tsx
  src/app/(route)/study/_components/AccordionTitle.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/common/Molecules/Form/SaveHeartButton.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/lib/schema.ts
  src/types/model/StudyCard.ts
Labels: merge

#136 Feature/study
  src/app/(route)/study/[studyPostId]/_components/ApplyButton.tsx
  src/app/(route)/study/[studyPostId]/_components/LeaderProfile.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailContent.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailThumbnail.tsx
  src/app/(route)/study/_components/AccordionList.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/LargeStudyList.tsx
  src/app/(route)/study/_components/StudyCardFilter.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/create/_components/StudyForm.tsx
  src/app/(route)/study/create/page.tsx
  src/app/api/study/route.ts
  src/common/Molecules/Profile.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/lib/actions/studyAction.ts
  src/lib/schema.ts
  src/types/model/StudyCard.ts
Labels: merge, 검토중, feature

#138 [Fix] 예외 처리 추가, 더미 데이터 연결 삭제
  src/app/(route)/_components/LikeIconButton.tsx
  src/app/(route)/my/post/page.tsx
  src/app/(route)/my/profile/_components/DeleteAccountConfirm.tsx
  src/app/(route)/my/profile/_components/EditProfileImage/FormEditProfileImageWithPreview.tsx
  src/app/(route)/my/profile/_components/EditProfileImage/ProfileImagePreviewModal.tsx
  src/app/(route)/my/study/page.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/_components/LinkedStudyCard.tsx
  src/app/_components/CategoryTab/MainSectionOfGoals.tsx
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/app/_components/NoneContentItemBase.tsx
  src/app/_components/RecommendLatestStudies.tsx
  src/app/_components/RecommendProStudies.tsx
  src/app/_components/UserCurrentStudy/ParticipatedInStudyStatusContent.tsx
  src/app/api/community/likes/[postId]/route.ts
  src/app/api/study-matching/favor/route.ts
  src/common/Templates/CardList.tsx
  src/dummies/comments.ts
  src/dummies/posts.ts
  src/dummies/studies.ts
  src/dummies/studypostdetail.ts
  src/middleware.ts
  src/store/likePostStore.ts
Labels: bug, bug fix

#139 [ Feat] studyForm ThumbnailImage api전송 테스트완
  src/app/(route)/study/create/_components/StudyForm.tsx
  src/app/(route)/study/create/_components/ThumbnailInput.tsx
  src/lib/actions/studyAction.ts
Labels: feature
