Repository woongteco/nextcamp-12t, pull requests merged in 2024-07, with the labels that each got.

#27 Feature/community post 1차 완료
  package-lock.json
  package.json
  public/icons/index.ts
  public/images/index.ts
  public/images/profile/DefaultProfile.png
  public/images/thumbnail/DefaultThumbnail.png
  src/app/(route)/layout.tsx
  src/app/(route)/post/[postId]/_components/LinkedStudyCard.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/page.tsx
  src/app/(route)/post/write/_components/SelectCategory.tsx
  src/app/(route)/post/write/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/common/Atoms/Form/Button.tsx
  src/common/Atoms/Form/DateRange.tsx
  src/common/Atoms/Form/Field.tsx
  src/common/Atoms/Form/InputElement.tsx
  src/common/Atoms/Form/Label.tsx
  src/common/Atoms/Form/QuillNoSSR.tsx
  src/common/Atoms/Form/SearchBar.tsx
  src/common/Atoms/Form/Select.tsx
  src/common/Atoms/Form/TextEditor.tsx
  src/common/Atoms/Form/customDateRange.css
  src/common/Atoms/Form/customInputElement.css
  src/common/Atoms/Form/customQuill.css
  src/common/Atoms/Image/Logo.tsx
  src/common/Atoms/Image/Profile.tsx
  src/common/Atoms/Image/ProfileImg.tsx
  src/common/Atoms/Image/Thumbnail.tsx
  src/common/Atoms/LinkButton.tsx
  src/common/Atoms/Text/Heading.tsx
  src/common/Atoms/Text/Keyword.tsx
  src/common/Atoms/Text/PageTitle.tsx
  src/common/Atoms/atomStyle.ts
  src/common/Layout/Container.tsx
  src/common/Layout/Footer.tsx
  src/common/Layout/Header.tsx
  src/common/Layout/Sidebar.tsx
  src/common/Layout/index.tsx
  src/common/Molecules/Dropdown.tsx
  src/common/Molecules/Form/ButtonCheck.tsx
  src/common/Molecules/Form/Input.tsx
  src/common/Molecules/Profile.tsx
  src/common/Organisms/Comment/CommentInput.tsx
  src/common/Organisms/Comment/CommentItem.tsx
  src/common/Organisms/ContentArea.tsx
  src/common/Organisms/PostListItem.tsx
  src/common/Organisms/StudyCard.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Organisms/customContent.module.css
  src/common/Templates/CommentArea.tsx
  src/dummies/categories.ts
  src/dummies/posts.ts
  src/dummies/studies.ts
  src/dummies/user.ts
  src/types/component/props.ts
  src/types/model/User.ts
  tailwind.config.ts
Labels: merge

#28 [Fix] svg 속성 warning 대응
  public/icons/404.svg
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/page.tsx
  src/common/Templates/CommentArea.tsx
Labels: bug fix

#40 [Style] : 기본으로 사용되는 study card 마크업, css
  package-lock.json
  package.json
  public/icons/heart.svg
  public/icons/index.ts
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/page.tsx
  src/common/Atoms/Text/PageTitle.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CardList.tsx
Labels: style

#41 Feature/study
  src/app/(route)/study/_components/GoodStudyItem.tsx
  src/app/(route)/study/_components/GoodStudyList.tsx
  src/app/(route)/study/_components/HotStudyItem.tsx
  src/app/(route)/study/_components/HotStudyList.tsx
  src/app/(route)/study/_components/NoneStudyComponent.tsx
  src/app/(route)/study/page.tsx
  src/common/Templates/CardList.tsx
Labels: style

#47 [Fix] react-select 사용시 id not match 오류 수정
  .prettierrc
  src/app/(auth)/login/_components/UserInput.tsx
  src/app/(route)/post/[postId]/_components/LinkedStudyCard.tsx
  src/app/_components/ReviewSection/UserReviewItem.tsx
  src/app/_components/ReviewSection/UserReviewSlider.tsx
  src/app/_components/TabButtonsOfGoalSection.tsx
  src/app/_components/TopBannerSection.tsx
  src/app/globals.css
  src/app/page.tsx
  src/common/Atoms/Form/Select.tsx
  src/common/Atoms/Image/Thumbnail.tsx
  src/common/Molecules/Profile.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CardList.tsx
  src/dummies/getImages.ts
  tailwind.config.ts
Labels: bug fix

#48 [Style] : 스터디페이지
  public/icons/index.ts
  public/icons/studyCategory/categoryIcon-application.svg
  public/icons/studyCategory/categoryIcon-challenge.svg
  public/icons/studyCategory/categoryIcon-hobby.svg
  public/icons/studyCategory/categoryIcon-jobinterview.svg
  public/icons/studyCategory/categoryIcon-learning.svg
  public/icons/studyCategory/categoryIcon-lecture.svg
  public/icons/studyCategory/categoryIcon-licensetest.svg
  public/icons/studyCategory/categoryIcon-offline.svg
  public/icons/studyCategory/categoryIcon-online.svg
  public/icons/studyCategory/categoryIcon-project.svg
  src/app/(route)/layout.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
Labels: style

#49 [Refactor] 커뮤니티 페이지 리팩토링
  package-lock.json
  package.json
  src/app/(route)/_components/ShareIconButton.tsx
  src/app/(route)/post/[postId]/_components/LinkedStudyCard.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/page.tsx
  src/app/(route)/post/write/page.tsx
  src/app/layout.tsx
  src/common/Atoms/Form/Button.tsx
  src/common/Atoms/Form/Field.tsx
  src/common/Atoms/Form/InputElement.tsx
  src/common/Atoms/Form/Select.tsx
  src/common/Atoms/Image/Thumbnail.tsx
  src/common/Layout/Sidebar/SideNavItem.tsx
  src/common/Layout/Sidebar/SidebarAsideContentArea.tsx
  src/common/Layout/Sidebar/SidebarNavArea.tsx
  src/common/Layout/_Sidebar.tsx
  src/common/Molecules/Alert.tsx
  src/common/Molecules/Dropdown.tsx
  src/common/Molecules/ModalPortal.tsx
  src/common/Molecules/ModalPortal/ModalBackdrop.tsx
  src/common/Molecules/ModalPortal/ModalLayer.tsx
  src/common/Molecules/ModalPortal/ModalPortal.tsx
  src/common/Molecules/NavMenu.tsx
  src/common/Molecules/Notification.tsx
  src/common/Molecules/Profile.tsx
  src/common/Organisms/LoginModal.tsx
  src/common/Organisms/Navigation.tsx
  src/common/Organisms/PostListItem.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/dummies/posts.ts
  src/dummies/user.ts
  src/types/component/props.ts
  src/types/model/User.ts
  tailwind.config.ts
Labels: merge, refactor, style

#50 [Style] study 페이지 스타일링 categorytablist 분리
  next.config.mjs
  public/icons/index.ts
  public/icons/studyCategory/categoryIcon-application.svg
  public/icons/studyCategory/categoryIcon-challenge.svg
  public/icons/studyCategory/categoryIcon-hobby.svg
  public/icons/studyCategory/categoryIcon-jobinterview.svg
  public/icons/studyCategory/categoryIcon-learning.svg
  public/icons/studyCategory/categoryIcon-lecture.svg
  public/icons/studyCategory/categoryIcon-licensetest.svg
  public/icons/studyCategory/categoryIcon-offline.svg
  public/icons/studyCategory/categoryIcon-online.svg
  public/icons/studyCategory/categoryIcon-project.svg
  src/app/(route)/study/_components/GoodStudyList.tsx
  src/app/(route)/study/_components/HotStudyList.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/LargeStudyList.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/_components/WideStudyList.tsx
  src/app/(route)/study/_components/icon/StudyCategoryIcons.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/app/_components/TabButtonsOfGoalSection.tsx
  src/common/Atoms/Image/Icon.tsx
  src/common/Layout/Sidebar.tsx
  src/common/Layout/index.tsx
  src/common/Templates/CardList.tsx
  src/dummies/categories.ts
Labels: merge, style

#55 [Style] Study 상세페이지
  public/icons/Arrow.svg
  public/icons/BadgeIcon.svg
  public/icons/QandAIcon.svg
  public/icons/details/calendar.svg
  public/icons/details/category.svg
  public/icons/details/expense.svg
  public/icons/details/onoff.svg
  public/icons/details/people.svg
  public/icons/fullheart.svg
  public/icons/index.ts
  public/icons/saveheart-sm.svg
  public/icons/share.svg
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/AccordionList.tsx
  src/app/(route)/study/_components/AccordionTitle.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/common/Atoms/Form/InputElement.tsx
  src/common/Atoms/Image/ProfileImg.tsx
  src/common/Organisms/Comment/CommentInput.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CommentArea.tsx
  src/dummies/studypostdetail.ts
Labels: style

#62 Feature/auth
  .gitignore
  package-lock.json
  package.json
  src/app/(auth)/_components/AuthWrap.tsx
  src/app/(auth)/_components/LoginForm.tsx
  src/app/(auth)/_components/LoginModal.tsx
  src/app/(auth)/_components/RegisterCheck.tsx
  src/app/(auth)/_components/RegisterForm.tsx
  src/app/(auth)/_components/UserInput.tsx
  src/app/(auth)/find/page.tsx
  src/app/(auth)/pw-reset/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(route)/my/layout.tsx
  src/app/_components/AuthSession.tsx
  src/app/_components/MainStatusBoard.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/auth.ts
  src/common/Layout/Header.tsx
  src/lib/action.ts
  src/lib/db.ts
  src/lib/schema.ts
  src/middleware.ts
  src/types/next-auth.d.ts
Labels: merge

#63 [Refactor, Feat] 머지 후 UnstyledLogoutButton 컴포넌트 분리
  src/app/(route)/_components/ShareIconButton.tsx
  src/app/(route)/layout.tsx
  src/app/(route)/my/layout.tsx
  src/app/(route)/my/profile/_components/FormEditProfile.tsx
  src/app/(route)/my/profile/page.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailThumbnailInfo.tsx
  src/app/(route)/study/_components/StudyCategorySelectBox.tsx
  src/app/_components/ReviewSection/UserReviewSlider.tsx
  src/common/Atoms/Form/InputElement.tsx
  src/common/Atoms/Image/Icon.tsx
  src/common/Atoms/Text/Caption.tsx
  src/common/Layout/Header.tsx
  src/common/Layout/Sidebar.tsx
  src/common/Layout/UnstyledLogoutButton.tsx
  src/common/Molecules/DefaultSwiper.tsx
Labels: bug fix, refactor

#69 [Chore] : 스터디관련 컴포넌트 구조 추가, 더미데이터 네이밍 등, 스타일 수정
  src/app/(route)/study/[studyPostId]/_components/Comment.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetail.tsx
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/StudyCategorySelectBox.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/app/_components/CategoryTab/TabIcons.tsx
  src/dummies/studypostdetail.ts
Labels: refactor, style, directory

#70 [Style] : header Profile구역 Style 수정
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/common/Layout/Header.tsx
Labels: style

#72 [Fix] 배포 빌드 오류로 로고 파일명 대문자 -> 소문자 수정
  public/icons/index.ts
  src/app/(route)/my/page.tsx
Labels: bug fix, deploy

#94 Feature/study
  package-lock.json
  package.json
  public/icons/index.ts
  public/icons/logo/Logo.svg
  src/app/(route)/_components/SearchInput.tsx
  src/app/(route)/study/[studyPostId]/_components/Comment.tsx
  src/app/(route)/study/[studyPostId]/_components/LeaderProfile.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetail.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailContent.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailThumbnail.tsx
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/Accordion.tsx
  src/app/(route)/study/_components/AccordionComponent.tsx
  src/app/(route)/study/_components/AccordionList.tsx
  src/app/(route)/study/_components/AccordionTitle.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/LargeStudyList.tsx
  src/app/(route)/study/_components/StudyCategorySelectBox.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/_components/WideStudyList.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/app/_components/CategoryTab/TabIcons.tsx
  src/app/_components/RecommendLatestStudies.tsx
  src/app/_components/RecommendProStudies.tsx
  src/common/Atoms/Text/Keyword.tsx
  src/common/Molecules/Form/SaveHeartButton.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CardList.tsx
  src/common/Templates/CommentArea.tsx
  src/dummies/studies.ts
  src/dummies/studypostdetail.ts
  src/hooks/useQueryString.tsx
Labels: bug fix

#95 [0.2.1] 스터디 탐색 페이지의 필터링 기능 보완
  package-lock.json
  package.json
  public/icons/index.ts
  public/icons/logo/Logo.svg
  src/app/(route)/_components/SearchInput.tsx
  src/app/(route)/study/[studyPostId]/_components/Comment.tsx
  src/app/(route)/study/[studyPostId]/_components/LeaderProfile.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetail.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailContent.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetailThumbnail.tsx
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/Accordion.tsx
  src/app/(route)/study/_components/AccordionComponent.tsx
  src/app/(route)/study/_components/AccordionList.tsx
  src/app/(route)/study/_components/AccordionTitle.tsx
  src/app/(route)/study/_components/LargeStudyItem.tsx
  src/app/(route)/study/_components/LargeStudyList.tsx
  src/app/(route)/study/_components/StudyCategorySelectBox.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/(route)/study/_components/WideStudyItem.tsx
  src/app/(route)/study/_components/WideStudyList.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/app/_components/CategoryTab/TabButtonsOfGoalSection.tsx
  src/app/_components/CategoryTab/TabIcons.tsx
  src/app/_components/RecommendLatestStudies.tsx
  src/app/_components/RecommendProStudies.tsx
  src/common/Atoms/Text/Keyword.tsx
  src/common/Molecules/Form/SaveHeartButton.tsx
  src/common/Organisms/StudyCardItem.tsx
  src/common/Templates/CardList.tsx
  src/common/Templates/CommentArea.tsx
  src/dummies/studies.ts
  src/dummies/studypostdetail.ts
  src/hooks/useQueryString.tsx
Labels: merge, deploy, feature

#99 [Style] : 스터디 개설하기
  public/icons/Edit/Vector.svg
  src/app/(route)/layout.tsx
  src/app/(route)/post/write/page.tsx
  src/app/(route)/study/[studyPostId]/page.tsx
  src/app/(route)/study/_components/StudyCategoryTabButtonList.tsx
  src/app/(route)/study/create/_components/CompleteButton.tsx
  src/app/(route)/study/create/_components/FormComponent.tsx
  src/app/(route)/study/create/page.tsx
  src/app/(route)/study/page.tsx
  src/app/(route)/study/search/page.tsx
  src/common/Atoms/Form/DateRange.tsx
  src/common/Atoms/Form/Field.tsx
  src/common/Atoms/Form/Select.tsx
  src/common/Atoms/Image/Icon.tsx
  src/common/Layout/Sidebar/SidebarAsideContentArea.tsx
  src/hooks/useQueryString.tsx
Labels: style

#102 [Feat, Fix] 더미 데이터 함수 수정, 프로필 액션 테스트 중
  src/app/(route)/_components/SearchInput.tsx
  src/app/(route)/my/like-study/page.tsx
  src/app/(route)/my/post/page.tsx
  src/app/(route)/my/profile/_components/FormEditProfile.tsx
  src/app/(route)/my/profile/_components/ProfileForms.tsx
  src/app/(route)/my/profile/_components/ProfileImageInput.tsx
  src/app/(route)/my/profile/page.tsx
  src/app/(route)/my/study/page.tsx
  src/app/(route)/post/[postId]/page.tsx
  src/app/(route)/post/_components/LinkedStudyCard.tsx
  src/app/(route)/post/_components/NonePostItem.tsx
  src/app/(route)/post/_components/ReturnToListButton.tsx
  src/app/(route)/post/page.tsx
  src/app/(route)/post/write/page.tsx
  src/app/(route)/study/[studyPostId]/_components/StudyDetail.tsx
  src/app/(route)/study/_components/NoneStudyComponent.tsx
  src/app/_components/NoneContentItemBase.tsx
  src/app/_components/UserCurrentStudySection.tsx
  src/common/Atoms/Form/Field.tsx
  src/common/Atoms/Form/QuillNoSSR.tsx
  src/common/Atoms/Form/TextEditor.tsx
  src/common/Atoms/Form/customQuill.css
  src/common/Layout/Header.tsx
  src/common/Layout/ProfileMenu/CreateStudyLink.tsx
  src/common/Layout/ProfileMenu/MobileMenu.tsx
  src/common/Layout/ProfileMenu/UserAlarm.tsx
  src/common/Layout/Sidebar/SidebarNavArea.tsx
  src/common/Molecules/SidePopup.tsx
  src/common/Organisms/Comment/CommentInput.tsx
  src/common/Organisms/Comment/CommentItem.tsx
  src/common/Organisms/PostListItem.tsx
  src/common/Organisms/customContent.module.css
  src/common/Templates/CommentArea.tsx
  src/common/Templates/PostListWithPagination.tsx
  src/constants/categories/job_category.ts
  src/dummies/comments.ts
  src/dummies/getImages.ts
  src/dummies/posts.ts
  src/dummies/studies.ts
  src/hooks/useQueryString.tsx
  src/lib/action.ts
  src/lib/schema.ts
  src/types/model/Comment.ts
  src/types/model/PostItem.ts
  src/types/model/Profile.ts
  src/types/model/User.ts
Labels: bug fix, refactor, style
